# Generated by Django 4.1.7 on 2023-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barbershop', '0003_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer_phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
