# Generated by Django 4.1.7 on 2023-03-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barbershop', '0004_alter_appointment_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer_phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
