# Generated by Django 4.1.7 on 2023-03-26 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barbershop', '0006_remove_barber_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
