# Generated by Django 2.2.16 on 2023-03-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barbershop', '0007_alter_service_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='barber',
            new_name='barber_name',
        ),
        migrations.RenameField(
            model_name='barber',
            old_name='barber_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='barber',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
