# Generated by Django 4.1.7 on 2023-04-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barbershop', '0009_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='name',
            new_name='barber_name',
        ),
    ]
