###

GET http://localhost:8000/api/v1/services/
Content-Type: application/json

{
    "master": "1",
    "barber_name": "master2_name",
    "phone_number": "+79999999991"
}

###

POST http://localhost:8000/api/v1/records/
Content-Type: application/json

{
    "date": "2023-04-01",
    "time": "10:00:00",
    "service": "cut the penis",
    "barber": "master2_name"
}
